### PR TITLE
Improve parsing

### LINKED ISSUE #5: New messages no longer shown
Somehow I can't see new message on Hangish, while I see them in Hangouts. Also one Conversation is completely gone. I was using 0.2.6b

Seems like the protocol changed again?

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Partial link support and fix parsing of [ and ] in message, this fixes #5

### CODE REVIEW

**Comment by rogora** [comment]
Thanks for the contribution, this was on my todo list.
Unfortunately I can't test your code now, I will merge as soon as I'll be able to do it.

**Comment by lukedirtwalker** [comment]
No worries, I have some more commits for improved UI and hopefully faster parsing, is it fine to add them here or should I do a new PR?

**Comment by rogora** [comment]
Well, maybe it is better if you split the requests for UI and for parsing. Again, thanks for the contribution, I appreciate it.

**Comment by lukedirtwalker** [comment]
Sure thing, I will do 2 new PR once this is merged.

**Comment by lukedirtwalker** [comment]
Hm it seems I can no longer send messages and the app goes offline. Not sure if it is related to this PR, so please make sure that it doesn't happen for you with this PR.

**Comment by rogora** [comment]
I confirm that the problem is caused by your "Fix #5" commit, that causes the client id not to be parsed, as a consequence of strings like " "[\"ci:ec\",1,1,0,\"chat_wcs_20141117.120048_RC4\"]\n" " being parsed as multiple fields.

I'll give a more detailed look at this asap.

**Comment by lukedirtwalker** [comment]
I added another commit which should workaround the issues introduced by 48c23ef
This is getting a bit ugly but it works :P

**Comment by lukedirtwalker** [comment]
Hm nevermind, it doesn't seem to be fully fixed yet.

**Comment by lukedirtwalker** [comment]
Superseded by #8

**Pull request closed without merging**
